### ISSUE TITLE
Make uft-tool docker swarm friendly

### ISSUE THREAD

**Issue by Stephenitis** [ClusterHQ/unofficial-flocker-tools#48]
notes in progress...

uft-flocker-install cluster.yml --swarm or
uft-flocker-install cluster.yml  docker-H tcp://0.0.0.0:2375

on master node
1. docker run --rm swarm create
2. export clusterkey to localhost?

_terraform_
Open Inbound Ports (2375 from internal, 2357 from external My IP) Need to reference the correct VPC ID when you create the sec group as well. Also open any other ports that your application may use, like 8080 ￼

**Comment by wallnerryan** [comment]
- I like the `--swarm` approach.
- "uft-flocker-install cluster.yml docker-H tcp://0.0.0.0:2375" actually won't work, as the swarm manager needs to run on a different port than the docker daemon
- the clusterkey doesn't have to be that unique, we could actually just run `swarm create` locally on the boot2docker machine and use that key. If uft tools are installed we already have docker locally. Otherwise yes, we could get the key from any node in the cluster and export it for the installer to use for swarm setup.
- the terraform template does this today, but it opens port 80 only. Its hard to expose this functionality ahead of time, as it only pertains to the demo and if you already know what will be running on the aws vpc.  Would be nice to have something dynamic like "open ports in existing uft cluster because im going to deploy this app" without having to touch anything provider specifics tooling (vbox forwarding, aws sec groups, etc)

**Comment by wallnerryan** [comment]
https://github.com/wallnerryan/unofficial-flocker-tools/tree/swarm-integration does this for Ubuntu on AWS

```
-> uft-flocker-config cluster.yml --swarm
Initialized cluster CA.
Created control cert.
Generated 18c9c57a-4529-438e-9742-02737cc0e11d for 52.8.59.116
Generated 03f71b6c-7132-452a-9884-87911fd6900d for 52.8.109.65
Created user key for user
Making /etc/flocker directory on all nodes
Uploading keys to respective nodes:
 * Uploaded control cert & key to control node.
 * Uploaded control key to ec2-52-8-114-153.us-west-1.compute.amazonaws.com
 * Uploaded cluster cert to ec2-52-8-114-153.us-west-1.compute.amazonaws.com
 * Uploaded control crt to ec2-52-8-114-153.us-west-1.compute.amazonaws.com
 * Uploaded cluster cert to 52.8.59.116
 * Uploaded cluster cert to 52.8.109.65
 * Uploaded node crt to 52.8.109.65
 * Uploaded node crt to 52.8.59.116
 * Uploaded agent.yml to 52.8.59.116
 * Uploaded node key to 52.8.109.65
 * Uploaded node key to 52.8.59.116
 * Uploaded agent.yml to 52.8.109.65
Created Swarm ID
Started Swarm Agent for 52.8.59.116
Started Swarm Agent for 52.8.109.65
Started Swarm Master
Swarm Master is at tcp://ec2-52-8-114-153.us-west-1.compute.amazonaws.com:2357
```

ping @luke @Stephenitis

**Comment by wallnerryan** [comment]
see PR for updates, if merged will close. https://github.com/ClusterHQ/unofficial-flocker-tools/pull/49
